name: Github Ananı Avradini

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Senin kendi EKVATOR cihaz ağacını indiriyoruz
      - name: Checkout Device Tree
        uses: actions/checkout@v4
        with:
          path: device_tree

      # Step 2: TWRP 11 Minimal Manifest deposunu GitHub'ın KENDİ İÇ MOTORUYLA doğrudan 'workspace' klasörüne çektiriyoruz! (cURL yok, tar.gz yok!)
      - name: Checkout Minimal TWRP Source (Lokal Çekim)
        uses: actions/checkout@v4
        with:
          repository: 'minimal-manifest-twrp/platform_manifest_twrp_omni'
          ref: 'twrp-11'
          path: workspace

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zlib1g-dev python3 python3-pip
          git config --global user.name "Builder"
          git config --global user.email "builder@action.com"
          
      - name: Inject Device Tree
        run: |
          # Klasör yapısını hazırlayıp cihaz ağacını içeri uçuruyoruz
          mkdir -p workspace/device/vestel/EKVATOR
          cp -r device_tree/* workspace/device/vestel/EKVATOR/
          
      - name: Start Compilation
        run: |
          cd workspace
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch omni_EKVATOR-eng
          mka recoveryimage

      - name: Upload TWRP Recovery Image
        uses: actions/upload-artifact@v4
        with:
          name: twrp-EKVATOR-image
          path: workspace/out/target/product/EKVATOR/recovery.img

